### ISSUE TITLE
Configurations should not be hardcoded

### ISSUE THREAD

**Issue by cupojoe** [j796160836/bitrise-step-code-signing-setting-patch#1]
Problem:

If your configurations are not Debug and Release you get the following error:

```ruby
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise897610484/step_src/edit.rb:45:in `getBuildSettingsStrings': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise897610484/step_src/edit.rb:58:in `block in printAllBuildSettings'
	from /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise897610484/step_src/edit.rb:56:in `each'
	from /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise897610484/step_src/edit.rb:56:in `printAllBuildSettings'
	from /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise897610484/step_src/edit.rb:65:in `<main>'
```

Configurations should be specifiable by the user in the step config, not hardcoded:

https://github.com/j796160836/bitrise-step-code-signing-setting-patch/blob/99a14f5751560cd6fb1737907a1bc698a62394a1/edit.rb#L18

This should be a param from the step config.

**Comment by j796160836** [comment]
Thanks for issue the problem, I will open the parameters for step config.
Generally it use "Debug" & "Release"

**Comment by OlesenkoViktor** [comment]
Have this issue both for Manual and Automatic code sign.
Used web Workflow Editor for setup
Can you please help, what I should do?

<img width="1199" alt="Screenshot 2021-05-11 at 11 17 03" src="https://user-images.githubusercontent.com/15200601/117786409-2271ab00-b24e-11eb-9309-0735dfd59c8d.png">

**Comment by Sweefties** [comment]
Hi, I'd like to suggest a small change : 

https://github.com/j796160836/bitrise-step-code-signing-setting-patch/pull/2

**Comment by huseyinmetin** [comment]
When will be deploy to bitrise? still using 1.0.4 version without this development.

**Comment by seyfeddin** [comment]
> When will be deploy to bitrise? still using 1.0.4 version without this development.

@j796160836 how can we open up a pull request on [bitrise/steplib](https://github.com/bitrise-io/bitrise-steplib/pulls)? Is it something only you can do?

**Comment by j796160836** [comment]
Hi seyfeddin,
Thanks to reach and notify me, as my work changes. I'm too busy for maintain this project.
I just do the version updates PR yesterday, stay tuned, thanks.

**Comment by seyfeddin** [comment]
Thank you!

**Comment by j796160836** [comment]
https://github.com/bitrise-io/bitrise-steplib/pull/4382

Looks it merged, please kindly try it, thanks.
